[toolchain]
package_manager = "yarn"
 anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
tickmyshow = "5FFwn1xD4ae3kttPDNoHmnW2x2tfekLQXUbRiaj6mBeG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

