[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tickmyshow = "5FFwn1xD4ae3kttPDNoHmnW2x2tfekLQXUbRiaj6mBeG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

